services:
  database:
    image: postgres:alpine
    restart: always
    container_name: database
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'workout'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
